main: com.diamonddagger590.caa.main.CrazyAuctionsAnnouncer
version: 1.1.3.1
name: CrazyAuctionsAnnouncer
api-version: 1.13
depend: [CrazyAuctions]
commands:
  caa:
    description: The main command for the CrazyAuctionsAnnouncer Plugin